### ISSUE TITLE
upgrade required error 

### ISSUE THREAD

**Issue by dileep9490** [gofiber/websocket#120]
This is the code i'm using which is copied from the readme.md 
when i'm running this code locally im getting upgrade required error
![websocket error](https://user-images.githubusercontent.com/63330310/178430579-fcefabb4-3338-4f3f-9948-3e4027b0678e.png)

**Comment by gabaudette** [comment]
Bump

**Comment by boombaw** [comment]
when i try to https, im getting upgrade required error

**Comment by pavittarsingh315** [comment]
I am getting the same error as of 1-18-2023.

**Comment by pavittarsingh315** [comment]
I have identified the issue in my case.

Basically, I was treating the websocket endpoint as a standard REST endpoint and was navigating to it using the browser. For example, say the websocket connection was at `localhost:8080/ws`. I was trying to navigate to this url in the browser which of course wouldn't work since the connect needs to be upgraded.

You need to make use of the `WebSocket` object in javascript to upgrade your request. An example of that can be found [here](https://github.com/gofiber/recipes/tree/master/websocket-chat) in the html file.

**Comment by gaby** [comment]
@dileep9490 @boombaw As stated by @pavittarsingh315 your code has to create a websocket connection to the server. You won't be able to access the websocket endpoint by using a browser directly. 

Take a look at this line: https://github.com/gofiber/recipes/blob/master/websocket-chat/home.html#L34
